version: "3.9"

networks:
  kaspiparse:
      driver: bridge

volumes:
    postgres_db:

services:
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: kaspiparse_nginx
    networks:
      - kaspiparse

  php:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
        -   "9000:9000"
    container_name: kaspiparse_php
    depends_on:
        -   postgres
    networks:
      - kaspiparse

  postgres:
    image: postgres:latest
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456ss
      POSTGRES_DB: kaspiparse_db
    container_name: kaspiparse_postgres
    networks:
      - kaspiparse

  composer:
    build:
      context: ./docker
      dockerfile: composer/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: kaspiparse_composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php
    user: laravel
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - kaspiparse

  npm:
    image: node:latest
    container_name: kaspiparse_npm
    volumes:
      - ./:/var/www
    ports:
      - 3010:3000
      - 3011:3001
    working_dir: /var/www
    entrypoint: [ 'npm' ]
    networks:
      - kaspiparse

  artisan:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: kaspiparse_artisan
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - postgres
    working_dir: /var/www
    entrypoint: [ 'php', '/var/www/artisan' ]
    networks:
      - kaspiparse

  redis:
    image: redis:latest
    container_name: kaspiparse_redis
    ports:
      - "6380:6379"
    restart: unless-stopped
    networks:
      - kaspiparse
